services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: logs_user
      POSTGRES_PASSWORD: logs_password
      POSTGRES_DB: logs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U logs_user -d logs_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
   build: .
   ports:
    - "8080:8080"
   environment:
    DATABASE_URL: postgres://logs_user:logs_password@db:5432/logs_db
   depends_on:
    db:
      condition: service_healthy



volumes:
  postgres_data:
